sudo: required
services:
  - docker

before_install:
  - docker build -t sjshekhar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sjshekhar/react-test npm test

after_success:
  - docker build -t sjshekhar/multi-client ./client
  - docker build -t sjshekhar/multi-nginx ./nginx
  - docker build -t sjshekhar/multi-server ./server
  - docker build -t sjshekhar/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sjshekhar/multi-client
  - docker push sjshekhar/multi-nginx
  - docker push sjshekhar/multi-server
  - docker push sjshekhar/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env:  MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-792612082302
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
